create table "public"."accounts" (
    "fid" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "private_key" text not null,
    "custody_address" text not null,
    "signer_uuid" text
);


alter table "public"."accounts" enable row level security;

CREATE UNIQUE INDEX accounts_pkey ON public.accounts USING btree (fid);

alter table "public"."accounts" add constraint "accounts_pkey" PRIMARY KEY using index "accounts_pkey";



